services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: peoplepad-backend
    restart: always
    depends_on:
      - db
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend:/app
      - /app/__pycache__  # optional: keeps host from filling with pycache
    environment:
        - PYTHONUNBUFFERED=1

  db:
    image: pgvector/pgvector:pg17
    container_name: peoplepad-db
    restart: always
    env_file:
      - ./backend/.env
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  embedding-service:
    build:
      context: ./embedding-service
      dockerfile: Dockerfile
    container_name: embedding-service
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./embedding-service:/app
    env_file: ./embedding-service/.env
    command: uvicorn app.main:app --host 0.0.0.0 --port 8080 --reload
volumes:
  pgdata:
