"""refresh token table

Revision ID: 9fb8fda4ce12
Revises: e568ac25d616
Create Date: 2025-10-02 20:00:41.772635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fb8fda4ce12'
down_revision = 'e568ac25d616'
branch_labels = None
depends_on = None


def upgrade():
    """Apply the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('hashed_token', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_records_embedding', 'records', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_l2_ops'})
    # ### end Alembic commands ###


def downgrade():
    """Revert the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_records_embedding', table_name='records', postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_l2_ops'})
    op.drop_table('refresh_tokens')
    # ### end Alembic commands ###