"""add salt column to tokens

Revision ID: bee06c6d5532
Revises: 9fb8fda4ce12
Create Date: 2025-10-02 20:10:21.979792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bee06c6d5532'
down_revision = '9fb8fda4ce12'
branch_labels = None
depends_on = None


def upgrade():
    """Apply the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_tokens', sa.Column('salt', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    """Revert the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('refresh_tokens', 'salt')
    # ### end Alembic commands ###