"""created at and last login user columns

Revision ID: e568ac25d616
Revises: 20250923_init
Create Date: 2025-09-30 20:30:28.433104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e568ac25d616'
down_revision = '20250923_init'
branch_labels = None
depends_on = None


def upgrade():
    """Apply the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_login', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    """Revert the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_column('users', 'last_login')
    # ### end Alembic commands ###