"""support for local mpnet embedding model

Revision ID: eebd6960cdc3
Revises: bee06c6d5532
Create Date: 2025-10-27 13:58:14.480921

"""
from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision = 'eebd6960cdc3'
down_revision = 'bee06c6d5532'
branch_labels = None
depends_on = None


def upgrade():
    """Apply the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('records', sa.Column('all_mpnet_base_v2_embedding', Vector(dim=768), nullable=True))
    op.create_index('idx_records_all_mpnet_base_v2_embedding', 'records', ['all_mpnet_base_v2_embedding'], unique=False, postgresql_using='hnsw', postgresql_ops={'all_mpnet_base_v2_embedding': 'vector_cosine_ops'})
    # ### end Alembic commands ###


def downgrade():
    """Revert the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_records_all_mpnet_base_v2_embedding', table_name='records', postgresql_using='hnsw', postgresql_ops={'all_mpnet_base_v2_embedding': 'vector_cosine_ops'})
    op.drop_column('records', 'all_mpnet_base_v2_embedding')
    # ### end Alembic commands ###