"""migration to mpnet model, drop old embeddings

Revision ID: fa728d2c7f98
Revises: eebd6960cdc3
Create Date: 2025-11-01 23:33:59.486425

"""
from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision = 'fa728d2c7f98'
down_revision = 'eebd6960cdc3'
branch_labels = None
depends_on = None


def upgrade():
    """Apply the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_records_embedding', table_name='records', postgresql_using='hnsw')
    op.drop_column('records', 'embedding')
    # ### end Alembic commands ###


def downgrade():
    """Revert the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('records', sa.Column('embedding', Vector(dim=1536), autoincrement=False, nullable=True))
    op.create_index('idx_records_embedding', 'records', ['embedding'], unique=False, postgresql_using='hnsw')
    # ### end Alembic commands ###